import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header";
import Footer from "./Components/Footer";
import Provider from "./Components/Providers";
import axios from "axios";
require("dotenv").config();
const roboto = Roboto({
  subsets: ["latin"],
  weight: "300",
  style: "normal",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const getStatus = async (api, status, anime_status) => {
  try {
    const res = await axios.get(
      `http://localhost:3000/api/${api}?material_data.${anime_status}=${status}`
    );
    return {
      anime: res.data,
    };
  } catch (error) {
    console.error("Ошибка при получении данных:", error);
    return null;
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <Provider>
          <Header />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
